server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8081/realms/pomodoro}

management:
  endpoints:
    web:
      exposure:
        include: health,info
